[package]
name = "system4"
authors = ["13th Eye <jjhh@13theye.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { workspace = true }
nannou = { workspace = true }
nannou_osc = { workspace = true }
nannou_egui = { workspace = true }
nnpipe = { workspace = true }
objc2-app-kit = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
rayon = "1.8"
thread-priority = "2"
toml = { workspace = true }

[lib]
name = "system4"
path = "src/lib.rs"

[[bin]]
name = "system4"
path = "src/main.rs"
