[package]
name = "system4"
authors = ["13th Eye <jjhh@13theye.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = { version = "0.31", features = ["byot", "responses"] }
config = "0.15"
crossbeam-channel = "0.5"
egui = "0.23"
futures = "0.3"

nannou = "0.19"
nannou_osc = "0.19"
nannou_egui = "0.19"

objc2-app-kit = "0.3"
rand = "0.9"
rand_distr = "0.5"
rayon = "1.10"
schemars = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
thread-priority = "2"

fps = { path = "../13thlib/fps" }
nnpipe = { path = "../13thlib/nnpipe" }
prat = { path = "../13thlib/prat" }

[lib]
name = "system4"
path = "src/lib.rs"

[[bin]]
name = "system4"
path = "src/main.rs"
