# config.toml for System4
# ALL FIELDS ARE REQUIRED

[osc_send]
# OSC receiver's IP address (String)
target_addr = "127.0.0.1"
# OSC receiver's port.
target_port = 50452

[osc_receive]
receive_port = 50450

[osc_loop]
# loopback OSC sender
target_addr = "127.0.0.1"
target_port = 50450

[openai_service]
url = "http://localhost:1234/v1/responses"
model = "openai/gpt-oss-20b"
#system_prompt = "We are playing a rhythm game. I will send you a representation of a rhythm, and you will respond with a rhythm that will sound good when played with my rhythm. The rhythm is represented as filled and empty slots. Example: [OOXOOOXOOOXOOOXO] This represents a rhythm with a capacity of 16 subdivisions. The X's are the strikes of the rhythm. Respond with the same format and subdivision capacity as the one you are given in our conversation. Your response can include your thought process. If you want to include your thought process, put that in a new line after the rhythm, like this: \"[OOXOOXOOX]\nI chose this rhythm because...\"Then, compose a haiku that captures the reason why you chose this rhythm."
#system_prompt = "We are playing a rhythm game. I will send you a representation of a rhythm, and you will respond with a rhythm that will sound good when played with my rhythm. The rhythm is represented as filled and empty slots. Example: [OOXOOOXOOOXOOOXO] This represents a sequence with a capacity of 16 subdivisions. The X's are the strikes of the rhythm. You will respond in a different format, using the rhythm_response_object_schema provided to you. An explanation of the format is provided in the \"description\" field of the schema. If you cannot access the schema, respond with \"CAN'T ACCESS SCHEMA\". Generate velocity, length, and cutoff parameters that make sense for the rhythm. Generate a haiku that describes your thought process in creating the rhythm and include it in the \"haiku\" field in the schema."
system_prompt = "We are playing a rhythm game. I will send you a representation of a rhythm, and you will respond with a rhythm that be played with my rhythm. The rhythm is represented as a string of filled and empty slots. Example: [OOXOOOXOOOXOOOXO] This represents a sequence with a capacity of 16 subdivisions. The X's are the strikes of the rhythm. The rhythm parameters is are as an array of objects. Each object has the following fields: index, velocity, length, cutoff. Example: [{\"index\": 0, \"velocity\": 0.5, \"length\": 0.5, \"cutoff\": 0.5}] The index being 0 means it is the first slot in the sequence. The length, velocity, and cutoff values range from 0.0 - 1.0 and represent those parameters in the sound engine. The length of the sequence is the length of the array. You will respond using the rhythm_response_object_schema provided to you. An explanation of the format is provided in the \"description\" field of the schema. If you cannot access the schema, respond with \"CAN'T ACCESS SCHEMA\". Generate a rhythm that will complement my rhythm. Make it complex and interesting. Think about how it will be plauyed with my rhythm. Generate velocity, length, and cutoff parameters that complement my rhythm. Generate a haiku that describes your thought process in creating the rhythm and include it in the \"haiku\" field in the schema."


[speed]
# initial beats per minute (float)
bpm = 125.0

[rendering]
texture_width = 3840
texture_height = 2160
dpi_scale = 2.0

# Please don't change these
texture_samples = 1
arc_resolution = 25

[audience_window]
# The size of the audience window game render.
width = 1920
height = 1080

[performer_window]
# The size of the performer window game render.
# This size works well for Macbooks
width = 1097
height = 617

[control_window]
# The size of the control window UI.
width = 1512
height = 270

[particles]
limit = 10000



