# config.toml for System4
# ALL FIELDS ARE REQUIRED

[osc_send]
# OSC receiver's IP address (String, "xxx.xxx.xx.xx")
target_addr = "127.0.0.1"
# OSC receiver's port.
target_port = 50452

[osc_receive]
receive_port = 50450

[osc_loop]
# OSC loopback target
target_addr = "127.0.0.1"
target_port = 50450

[openai_service]
# use the following for local LMStudio
# url should follow the pattern: "http://_________:port/v1"
url = "http://localhost:1234/v1"
model = "openai/gpt-oss-20b"
# When "true", uses the strict adherence to OpenAI Responses API
# When "false", crams everything into the "input" field.
# Use "false" for LMStudio
strict_request_object_adherence = false

# use the following for Google Gemma. Untested.
#model = "models/gemma-3-27b-it"
#url = "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"
#api_key = "AIzaSyCvu1Ke0PH_2rGPrqp0V9Mx_iA2AwUPvys"
#strict_request_object_adherence = true

# use the following for all AI models
system_prompt = "We are playing a rhythm game. I will send you a rhythm, and you will generate a complex and interesting rhythm that will complement my rhythm when played at the same time. One exception: if my rhythm has one or two X's, you will generate a rhythm that has the same number of X's as my rhythm. If my rhythm has more than two X's, you can generate a rhythm with any number of X's. Consider how it will be played with my rhythm. Choose a beat subdivision that will advance the sequence. Generate velocity, length, and cutoff parameters for each note, taking care that each note's timbre and envelope complements the timbre and envelope of the corresponding notes in my rhythm. The rhythm is represented as a string of filled and empty slots. Example: --X---X- This represents a sequence with a capacity of 8 subdivisions. The X's are the strikes, and the -'s are silent. The rhythm parameters are an array of objects. Each object has the fields: index, velocity, length, cutoff. Example: [{\"i\": 0, \"v\": 0.5, \"l\": 0.5, \"c\": 0.5}] The index being 0 means it is the first slot in the sequence. The length, velocity, and cutoff values range from 0.0 - 1.0 and represent timbre and envelope parameters used in the external sound engine. The number of the objects in the array should be the same as the capacity of the sequence. Generate a sijo (시조) from Chosun dynasty that describes your thought process in creating the rhythm and include it in the \"feeling\" field in the schema. A sijo has three lines: the first line introduces the theme, the second line develops the tension, and the third resolves it with a surprising twist. The poem must be in English. The poem may be quite abstract -- use non-obvious metaphors. Respond in valid JSON using the rhythm_object_schema provided to you."

# Deprecated. Schema_description is now generated automatically from the code comments
# in the schema definition.
#schema_description = "The schema describes parameters needed to create a rhythm sequence. The \"capacity\" is the length of the sequence in beat subdivisions. The \"rhythm\" field is a String representing the rhythm sequence. - is note off, and X is note on. The number of X's and -'s should be equal to capacity. No other characters or whitespace are allowed. The field \"i\" is the 0-indexed positions of a note in the sequence. The fields \"v\", \"l\", and \"c\" are parameters describing the velocity, length, and cutoff of each note in the rhythm sequence. Each parameter is a number from 0.0 to 1.0. The \"poem\" field is a String containing the haiku that you are asked to write in the prompt."

[tempo]
# initial beats per minute (float i.e. 120.0)
bpm = 125.0

[rendering]
# The size of the texture. Whole numbers only, i.e. 3840
texture_width = 3840
texture_height = 2160
dpi_scale = 2.0

# Please don't change these
texture_samples = 1
arc_resolution = 25

[audience_window]
# The size of the audience window game render.
# Whole numbers only, i.e. 1920
width = 1920
height = 1080

[performer_window]
# The size of the performer window game render.
# 1097x617 works well for Macbooks Pro 14"
width = 1097
height = 617

[control_window]
# The size of the control window UI.
# Whole numbers only, i.e. 1512
width = 1512
height = 270

[particles]
# Maximum number of particles per voice. Whole numbers only.
per_voice_limit = 15000



