// Relevant types generated by OpenAI Responses Stream according to schema at
// https://platform.openai.com/docs/api-reference/responses/object
//
// This module now contains only the subset of types we actually use

use async_openai::types::responses::{self};
use serde::{Deserialize, Serialize};

use crate::openai::schema::response::{MessageContent, OutputItem, ResponseObject};

pub type ResponseStream = std::pin::Pin<
    Box<dyn futures::Stream<Item = Result<StreamEvent, async_openai::error::OpenAIError>> + Send>,
>;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(tag = "type")]
pub enum StreamEvent {
    /// An event that is emitted when a response is created.
    #[serde(rename = "response.created")]
    ResponseCreated(ResponseCreatedEvent),
    /// Emitted when the response is in progress.
    #[serde(rename = "response.in_progress")]
    ResponseInProgress(ResponseInProgressEvent),
    /// Emitted when the model response is complete.
    #[serde(rename = "response.completed")]
    ResponseCompleted(ResponseCompletedEvent),
    /// An event that is emitted when a response fails.
    #[serde(rename = "response.failed")]
    ResponseFailed(ResponseFailedEvent),
    /// An event that is emitted when a response finishes as incomplete.
    #[serde(rename = "response.incomplete")]
    ResponseIncomplete(ResponseIncompleteEvent),
    /// Emitted when a new output item is added.
    #[serde(rename = "response.output_item.added")]
    ResponseOutputItemAdded(ResponseOutputItemAddedEvent),
    /// Emitted when an output item is marked done.
    #[serde(rename = "response.output_item.done")]
    ResponseOutputItemDone(ResponseOutputItemDoneEvent),
    /// Emitted when a new content part is added.
    #[serde(rename = "response.content_part.added")]
    ResponseContentPartAdded(ResponseContentPartAddedEvent),
    /// Emitted when a content part is done.
    #[serde(rename = "response.content_part.done")]
    ResponseContentPartDone(ResponseContentPartDoneEvent),
    /// Emitted when there is an additional text delta.
    #[serde(rename = "response.output_text.delta")]
    ResponseOutputTextDelta(ResponseTextDeltaEvent),
    /// Emitted when text content is finalized.
    #[serde(rename = "response.output_text.done")]
    ResponseOutputTextDone(ResponseTextDoneEvent),
    /// Emitted when there is a partial refusal text.
    #[serde(rename = "response.refusal.delta")]
    ResponseRefusalDelta(ResponseRefusalDeltaEvent),
    #[serde(rename = "response.refusal.done")]
    /// Emitted when refusal text is finalized.
    ResponseRefusalDone(ResponseRefusalDoneEvent),
    /// Emitted when a delta is added to a reasoning text.
    #[serde(rename = "response.reasoning_text.delta")]
    ResponseReasoningTextDelta(ResponseReasoningTextDeltaEvent),
    /// Emitted when a reasoning text is completed.
    #[serde(rename = "response.reasoning_text.done")]
    ResponseReasoningTextDone(ResponseReasoningTextDoneEvent),
    /// Emitted when an error occurs.
    #[serde(rename = "error")]
    ResponseError(ResponseErrorEvent),
    /// Other types not supported here
    Unknown,
}

impl From<responses::ResponseStreamEvent> for StreamEvent {
    fn from(item: responses::ResponseStreamEvent) -> Self {
        match item {
            responses::ResponseStreamEvent::ResponseCreated(event) => {
                StreamEvent::ResponseCreated(ResponseCreatedEvent {
                    sequence_number: event.sequence_number,
                    response: ResponseObject::from(event.response),
                })
            }
            responses::ResponseStreamEvent::ResponseInProgress(event) => {
                StreamEvent::ResponseInProgress(ResponseInProgressEvent {
                    sequence_number: event.sequence_number,
                    response: ResponseObject::from(event.response),
                })
            }
            responses::ResponseStreamEvent::ResponseCompleted(event) => {
                StreamEvent::ResponseCompleted(ResponseCompletedEvent {
                    sequence_number: event.sequence_number,
                    response: ResponseObject::from(event.response),
                })
            }
            responses::ResponseStreamEvent::ResponseFailed(event) => {
                StreamEvent::ResponseFailed(ResponseFailedEvent {
                    sequence_number: event.sequence_number,
                    response: ResponseObject::from(event.response),
                })
            }
            responses::ResponseStreamEvent::ResponseIncomplete(event) => {
                StreamEvent::ResponseIncomplete(ResponseIncompleteEvent {
                    sequence_number: event.sequence_number,
                    response: ResponseObject::from(event.response),
                })
            }

            responses::ResponseStreamEvent::ResponseOutputItemAdded(event) => {
                StreamEvent::ResponseOutputItemAdded(ResponseOutputItemAddedEvent {
                    sequence_number: event.sequence_number,
                    output_index: event.output_index,
                    item: OutputItem::from(event.item),
                })
            }
            responses::ResponseStreamEvent::ResponseOutputItemDone(event) => {
                StreamEvent::ResponseOutputItemDone(ResponseOutputItemDoneEvent {
                    sequence_number: event.sequence_number,
                    output_index: event.output_index,
                    item: OutputItem::from(event.item),
                })
            }
            responses::ResponseStreamEvent::ResponseContentPartAdded(event) => {
                StreamEvent::ResponseContentPartAdded(ResponseContentPartAddedEvent {
                    sequence_number: event.sequence_number,
                    item_id: event.item_id,
                    output_index: event.output_index,
                    content_index: event.content_index,
                    part: MessageContent::from(event.part),
                })
            }
            responses::ResponseStreamEvent::ResponseContentPartDone(event) => {
                StreamEvent::ResponseContentPartDone(ResponseContentPartDoneEvent {
                    sequence_number: event.sequence_number,
                    item_id: event.item_id,
                    output_index: event.output_index,
                    content_index: event.content_index,
                    part: MessageContent::from(event.part),
                })
            }
            responses::ResponseStreamEvent::ResponseOutputTextDelta(event) => {
                StreamEvent::ResponseOutputTextDelta(ResponseTextDeltaEvent {
                    sequence_number: event.sequence_number,
                    item_id: event.item_id,
                    output_index: event.output_index,
                    content_index: event.content_index,
                    delta: event.delta,
                })
            }
            responses::ResponseStreamEvent::ResponseOutputTextDone(event) => {
                StreamEvent::ResponseOutputTextDone(ResponseTextDoneEvent {
                    sequence_number: event.sequence_number,
                    item_id: event.item_id,
                    output_index: event.output_index,
                    content_index: event.content_index,
                    text: event.text,
                })
            }
            responses::ResponseStreamEvent::ResponseRefusalDelta(event) => {
                StreamEvent::ResponseRefusalDelta(ResponseRefusalDeltaEvent {
                    sequence_number: event.sequence_number,
                    item_id: event.item_id,
                    output_index: event.output_index,
                    content_index: event.content_index,
                    delta: event.delta,
                })
            }
            responses::ResponseStreamEvent::ResponseRefusalDone(event) => {
                StreamEvent::ResponseRefusalDone(ResponseRefusalDoneEvent {
                    sequence_number: event.sequence_number,
                    item_id: event.item_id,
                    output_index: event.output_index,
                    content_index: event.content_index,
                    refusal: event.refusal,
                })
            }
            responses::ResponseStreamEvent::ResponseReasoningTextDelta(event) => {
                StreamEvent::ResponseReasoningTextDelta(ResponseReasoningTextDeltaEvent {
                    sequence_number: event.sequence_number,
                    item_id: event.item_id,
                    output_index: event.output_index,
                    content_index: event.content_index,
                    delta: event.delta,
                })
            }
            responses::ResponseStreamEvent::ResponseReasoningTextDone(event) => {
                StreamEvent::ResponseReasoningTextDone(ResponseReasoningTextDoneEvent {
                    sequence_number: event.sequence_number,
                    item_id: event.item_id,
                    output_index: event.output_index,
                    content_index: event.content_index,
                    text: event.text,
                })
            }
            responses::ResponseStreamEvent::ResponseError(event) => {
                StreamEvent::ResponseError(ResponseErrorEvent {
                    sequence_number: event.sequence_number,
                    code: event.code,
                    message: event.message,
                    param: event.param,
                })
            }

            _ => StreamEvent::Unknown,
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseCreatedEvent {
    pub sequence_number: u64,
    pub response: ResponseObject,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseInProgressEvent {
    pub sequence_number: u64,
    pub response: ResponseObject,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseCompletedEvent {
    pub sequence_number: u64,
    pub response: ResponseObject,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseFailedEvent {
    pub sequence_number: u64,
    pub response: ResponseObject,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseIncompleteEvent {
    pub sequence_number: u64,
    pub response: ResponseObject,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseOutputItemAddedEvent {
    pub sequence_number: u64,
    pub output_index: u32,
    pub item: OutputItem,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseOutputItemDoneEvent {
    pub sequence_number: u64,
    pub output_index: u32,
    pub item: OutputItem,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseContentPartAddedEvent {
    pub sequence_number: u64,
    pub item_id: String,
    pub output_index: u32,
    pub content_index: u32,
    pub part: MessageContent,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseContentPartDoneEvent {
    pub sequence_number: u64,
    pub item_id: String,
    pub output_index: u32,
    pub content_index: u32,
    pub part: MessageContent,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseTextDeltaEvent {
    pub sequence_number: u64,
    pub item_id: String,
    pub output_index: u32,
    pub content_index: u32,
    pub delta: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseTextDoneEvent {
    pub sequence_number: u64,
    pub item_id: String,
    pub output_index: u32,
    pub content_index: u32,
    pub text: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseRefusalDeltaEvent {
    pub sequence_number: u64,
    pub item_id: String,
    pub output_index: u32,
    pub content_index: u32,
    pub delta: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseRefusalDoneEvent {
    pub sequence_number: u64,
    pub item_id: String,
    pub output_index: u32,
    pub content_index: u32,
    pub refusal: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseReasoningTextDeltaEvent {
    pub sequence_number: u64,
    pub item_id: String,
    pub output_index: u32,
    pub content_index: u32,
    pub delta: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseReasoningTextDoneEvent {
    pub sequence_number: u64,
    pub item_id: String,
    pub output_index: u32,
    pub content_index: u32,
    pub text: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseErrorEvent {
    pub sequence_number: u64,
    pub code: Option<String>,
    pub message: String,
    pub param: Option<String>,
}
