// Relevant types generated by OpenAI Responses according to schema at
// https://platform.openai.com/docs/api-reference/responses/object
//
// This module now contains only the subset of types we actually use for
// parsing the `output` array of a ResponseObject: output messages,
// reasoning items, and their text content.

use serde::Deserialize;

/// An item in the `output` array. It can be either a standard assistant message
/// or a reasoning object.
#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum OpenAIOutputItem {
    Message(OpenAIOutputMessage),
    Reasoning(OpenAIOutputReasoning),
}

/// A single output item of type "message".
#[derive(Debug, Deserialize)]
pub struct OpenAIOutputMessage {
    pub id: String,
    /// Status of this message item; may be omitted in some responses.
    #[serde(default)]
    pub status: Option<String>,
    #[serde(rename = "type")]
    pub typ: String, // always "message"
    /// Role of the message sender (always "assistant" for output messages).
    pub role: String,
    /// Structured content blocks (text, refusal, etc.).
    pub content: Vec<OpenAIOutputContent>,
}

/// A reasoning object in the output array.
#[derive(Debug, Deserialize)]
pub struct OpenAIOutputReasoning {
    pub id: String,
    /// Status of this reasoning item; may be omitted in some responses.
    #[serde(default)]
    pub status: Option<String>,
    #[serde(rename = "type")]
    pub typ: String, // always "reasoning"
    /// Summary of the reasoning.
    pub summary: Vec<OpenAIReasoningText>,
    /// Full reasoning content.
    pub content: Vec<OpenAIReasoningText>,
}

/// A single content block within an output message.
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OpenAIOutputContent {
    /// Textual content.
    OutputText { text: String },
    /// Refusal message when the model declines to answer.
    OutputRefusal { refusal: String },
    /// Any other content type we are not explicitly modeling.
    #[serde(other)]
    Unknown,
}

/// One block of reasoning text, used in both `summary` and `content` of
/// reasoning items.
#[derive(Debug, Deserialize)]
pub struct OpenAIReasoningText {
    pub text: String,
    #[serde(rename = "type")]
    pub typ: String, // always "reasoning_text"
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub encrypted_content: Option<String>,
}
