// Relevant types generated by OpenAI Responses according to schema at
// https://platform.openai.com/docs/api-reference/responses/object
//
// This module now contains only the subset of types we actually use for
// parsing the `output` array of a ResponseObject: output messages,
// reasoning items, and their text content.

use async_openai::types::responses;
use serde::{Deserialize, Serialize};

/// The complete response returned by the Responses API.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseObject {
    /// Unix timestamp (in seconds) when this Response was created.
    pub created_at: u64,

    /// Error object if the API failed to generate a response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<responses::ErrorObject>,

    /// Unique identifier for this response.
    pub id: String,

    /// Details about why the response is incomplete, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub incomplete_details: Option<responses::IncompleteDetails>,

    /// The value of `max_output_tokens` that was honored.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<u32>,

    /// The array of content items generated by the model.
    /// This is using this crate's OutputContent type.
    pub output: Vec<OutputContent>,

    /// Previous response ID, if creating part of a multi-turn conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_response_id: Option<String>,

    /// Reasoning configuration echoed back (effort, summary settings).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<responses::ReasoningConfig>,

    /// The status of the response generation.
    pub status: responses::Status,

    /// Sampling temperature that was used.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,

    /// Text format configuration echoed back (plain, json_object, json_schema).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<responses::TextConfig>,

    /// Token usage statistics for this request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,

    /// End-user ID for which this response was generated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

/// An item in the `output` array. It can be either a standard assistant message
/// or a reasoning object.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(untagged)]
pub enum OutputContent {
    Message(OutputMessage),
    Reasoning(ReasoningItem),
}

/// A single output item of type "message".
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct OutputMessage {
    pub id: String,
    /// Status of this message item; may be omitted in some responses.
    #[serde(default)]
    pub status: Option<String>,
    #[serde(rename = "type")]
    pub typ: String, // always "message"
    /// Role of the message sender (always "assistant" for output messages).
    pub role: String,
    /// Structured content blocks (text, refusal, etc.).
    pub content: Vec<MessageContent>,
}

/// A reasoning object in the output array.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ReasoningItem {
    pub id: String,
    /// Status of this reasoning item; may be omitted in some responses.
    pub status: Option<String>,
    #[serde(rename = "type")]
    pub typ: String, // always "reasoning"
    /// Summary of the reasoning.
    pub summary: Vec<ReasoningContent>,
    /// Full reasoning content.
    pub content: Vec<ReasoningContent>,
}

/// A single content block within an output message.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MessageContent {
    /// Textual content.
    OutputText { text: String },
    /// Refusal message when the model declines to answer.
    Refusal { refusal: String },
    /// Any other content type we are not explicitly modeling.
    #[serde(other)]
    Unknown,
}

/// One block of reasoning text, used in both `summary` and `content` of
/// reasoning items.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ReasoningContent {
    pub text: String,
    #[serde(rename = "type")]
    pub typ: String, // always "reasoning_text"
    #[serde(default)]
    pub status: Option<String>,
    #[serde(default)]
    pub encrypted_content: Option<String>,
}

/// Usage statistics for a response.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct Usage {
    /// The number of input tokens.
    pub input_tokens: u32,
    /// A detailed breakdown of the input tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_tokens_details: Option<responses::PromptTokensDetails>,
    /// The number of output tokens.
    pub output_tokens: u32,
    /// A detailed breakdown of the output tokens.
    pub output_tokens_details: responses::CompletionTokensDetails,
    /// The total number of tokens used.
    pub total_tokens: u32,
}
