// Relevant types generated by OpenAI Responses according to schema at
// https://platform.openai.com/docs/api-reference/responses/object

use serde::Deserialize;

/// Minimal model of an OpenAI Responses object as returned by the API.
///
/// This intentionally omits many optional/unused fields.
#[derive(Debug, Deserialize)]
pub struct OpenAIResponse {
    pub id: String,
    pub object: String,
    /// Unix timestamp in seconds.
    pub created_at: i64,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<OpenAIError>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub incomplete_details: Option<OpenAIIncompleteDetails>,
    pub model: String,
    /// Items in the output array; this app currently only models message items.
    pub output: Vec<OpenAIOutputMessage>,
    /// Optional reasoning summary data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<OpenAIReasoning>,
    /// Optional token usage information.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<OpenAIUsage>,
}

#[derive(Debug, Deserialize)]
pub struct OpenAIError {
    pub code: String,
    pub message: String,
}

#[derive(Debug, Deserialize)]
pub struct OpenAIIncompleteDetails {
    pub reason: String,
}

/// A single output item of type "message".
#[derive(Debug, Deserialize)]
pub struct OpenAIOutputMessage {
    pub id: String,
    pub status: String,
    #[serde(rename = "type")]
    pub typ: String, // e.g. "message"
    /// Role of the message sender (e.g. "assistant").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Structured content blocks (text, refusal, etc.).
    pub content: Vec<OpenAIOutputContent>,
}

/// A single content block within an output message.
#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OpenAIOutputContent {
    /// Textual content.
    OutputText { text: String },
    /// Refusal message when the model declines to answer.
    OutputRefusal { refusal: String },
    /// Any other content type we are not explicitly modeling.
    #[serde(other)]
    Unknown,
}

#[derive(Debug, Deserialize)]
pub struct OpenAIUsage {
    pub input_tokens: u64,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_tokens_details: Option<OpenAIUsageInputTokensDetails>,
    pub output_tokens: u64,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens_details: Option<OpenAIUsageOutputTokensDetails>,
    #[serde(default)]
    pub total_tokens: u64,
}

#[derive(Debug, Deserialize)]
pub struct OpenAIUsageInputTokensDetails {
    #[serde(default)]
    pub cached_tokens: u64,
}

#[derive(Debug, Deserialize)]
pub struct OpenAIUsageOutputTokensDetails {
    #[serde(default)]
    pub reasoning_tokens: u64,
}

#[derive(Debug, Deserialize)]
pub struct OpenAIReasoning {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn deserializes_minimal_response_without_reasoning_or_usage() {
        let value = json!({
            "id": "resp_123",
            "object": "response",
            "created_at": 1_700_000_000,
            "status": "completed",
            "model": "openai/gpt-oss-20b",
            "output": [
                {
                    "id": "msg_1",
                    "status": "completed",
                    "type": "message",
                    "role": "assistant",
                    "content": [
                        {
                            "type": "output_text",
                            "text": "Hello, world!"
                        }
                    ]
                }
            ]
        });

        let resp: OpenAIResponse =
            serde_json::from_value(value).expect("failed to deserialize minimal response");

        assert_eq!(resp.id, "resp_123");
        assert_eq!(resp.object, "response");
        assert_eq!(resp.created_at, 1_700_000_000);
        assert_eq!(resp.status, "completed");
        assert!(resp.reasoning.is_none());
        assert!(resp.usage.is_none());
        assert_eq!(resp.output.len(), 1);

        let msg = &resp.output[0];
        assert_eq!(msg.id, "msg_1");
        assert_eq!(msg.status, "completed");
        assert_eq!(msg.typ, "message");
        assert_eq!(msg.role.as_deref(), Some("assistant"));
        assert_eq!(msg.content.len(), 1);

        match msg.content[0] {
            OpenAIOutputContent::OutputText { ref text } => {
                assert_eq!(text, "Hello, world!");
            }
            _ => panic!("expected OutputText content"),
        }
    }

    #[test]
    fn deserializes_response_with_usage_reasoning_and_refusal() {
        let value = json!({
            "id": "resp_456",
            "object": "response",
            "created_at": 1_700_000_100,
            "status": "completed",
            "model": "openai/gpt-oss-20b",
            "output": [
                {
                    "id": "msg_2",
                    "status": "completed",
                    "type": "message",
                    "role": "assistant",
                    "content": [
                        {
                            "type": "output_refusal",
                            "refusal": "I cannot do that."
                        }
                    ]
                }
            ],
            "reasoning": {
                "effort": "high",
                "summary": "some reasoning summary"
            },
            "usage": {
                "input_tokens": 10,
                "output_tokens": 5,
                "total_tokens": 15,
                "input_tokens_details": {
                    "cached_tokens": 2
                },
                "output_tokens_details": {
                    "reasoning_tokens": 1
                }
            }
        });

        let resp: OpenAIResponse =
            serde_json::from_value(value).expect("failed to deserialize response with usage");

        assert!(resp.reasoning.is_some());
        let reasoning = resp.reasoning.unwrap();
        assert_eq!(reasoning.effort.as_deref(), Some("high"));
        assert_eq!(reasoning.summary.as_deref(), Some("some reasoning summary"));

        let usage = resp.usage.expect("usage should be present");
        assert_eq!(usage.input_tokens, 10);
        assert_eq!(usage.output_tokens, 5);
        assert_eq!(usage.total_tokens, 15);

        let input_details = usage
            .input_tokens_details
            .expect("input details should be present");
        assert_eq!(input_details.cached_tokens, 2);

        let output_details = usage
            .output_tokens_details
            .expect("output details should be present");
        assert_eq!(output_details.reasoning_tokens, 1);

        let msg = &resp.output[0];
        assert_eq!(msg.content.len(), 1);
        match msg.content[0] {
            OpenAIOutputContent::OutputRefusal { ref refusal } => {
                assert_eq!(refusal, "I cannot do that.");
            }
            _ => panic!("expected OutputRefusal content"),
        }
    }
}
