// Relevant types generated by OpenAI Responses according to schema at
// https://platform.openai.com/docs/api-reference/responses/object
//
// This module now contains only the subset of types we actually use for
// parsing the `output` array of a ResponseObject: output messages,
// reasoning items, and their text content.
//
// This module also contains methods to convert async-openai types to this crate's types.

use async_openai::types::responses;
use serde::{Deserialize, Serialize};

/// The complete response returned by the Responses API.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseObject {
    /// Unix timestamp (in seconds) when this Response was created.
    pub created_at: u64,

    /// Error object if the API failed to generate a response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ErrorObject>,

    /// Unique identifier for this response.
    pub id: String,

    /// Details about why the response is incomplete, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub incomplete_details: Option<IncompleteDetails>,

    /// The value of `max_output_tokens` that was honored.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<u32>,

    /// The array of content items generated by the model.
    /// This is using this crate's OutputContent type.
    pub output: Vec<OutputItem>,

    /// Previous response ID, if creating part of a multi-turn conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_response_id: Option<String>,

    /// Reasoning configuration echoed back (effort, summary settings).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<Reasoning>,

    /// The status of the response generation.
    pub status: Status,

    /// Sampling temperature that was used.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,

    /// Token usage statistics for this request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<ResponseUsage>,
}

impl From<responses::Response> for ResponseObject {
    fn from(item: responses::Response) -> Self {
        let output = item
            .output
            .into_iter()
            .map(|output_item| match output_item {
                responses::OutputItem::Message(message) => {
                    OutputItem::Message(OutputMessage::from(message))
                }
                responses::OutputItem::Reasoning(reasoning) => {
                    OutputItem::Reasoning(ReasoningItem::from(reasoning))
                }
                other => {
                    let val = serde_json::to_value(other).unwrap_or(serde_json::Value::Null);
                    OutputItem::Unknown(val)
                }
            })
            .collect();

        let error = item.error.map(ErrorObject::from);
        let incomplete_details = item.incomplete_details.map(IncompleteDetails::from);
        let reasoning = item.reasoning.map(Reasoning::from);
        let usage = item.usage.map(ResponseUsage::from);

        Self {
            created_at: item.created_at,
            error,
            id: item.id.to_owned(),
            incomplete_details,
            max_output_tokens: item.max_output_tokens.to_owned(),
            output,
            previous_response_id: item.previous_response_id.to_owned(),
            reasoning,
            status: Status::from(item.status),
            temperature: item.temperature.to_owned(),
            usage,
        }
    }
}

/// An item in the `output` array. It can be either a standard assistant message
/// or a reasoning object.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(untagged)]
pub enum OutputItem {
    Message(OutputMessage),
    Reasoning(ReasoningItem),
    // catchall for any other type that we are not explicitly modeling
    Unknown(serde_json::Value),
}

impl From<responses::OutputItem> for OutputItem {
    fn from(item: responses::OutputItem) -> Self {
        match item {
            responses::OutputItem::Message(message) => {
                OutputItem::Message(OutputMessage::from(message))
            }
            responses::OutputItem::Reasoning(reasoning) => {
                OutputItem::Reasoning(ReasoningItem::from(reasoning))
            }
            other => {
                let val = serde_json::to_value(&other).unwrap_or(serde_json::Value::Null);
                OutputItem::Unknown(val)
            }
        }
    }
}

/// A single output item of type "message".
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct OutputMessage {
    pub id: String,
    /// Status of this message item; may be omitted in some responses.
    #[serde(default)]
    pub status: Option<OutputStatus>,
    /// Structured content blocks (text, refusal, etc.).
    pub content: Vec<MessageContent>,
}

impl From<responses::OutputMessage> for OutputMessage {
    fn from(item: responses::OutputMessage) -> Self {
        let content = item.content.into_iter().map(MessageContent::from).collect();

        Self {
            id: item.id.to_owned(),
            status: Some(OutputStatus::from(item.status)),
            content,
        }
    }
}

/// A reasoning object in the output array.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ReasoningItem {
    pub id: String,
    /// Status of this reasoning item; may be omitted in some responses.
    pub status: Option<OutputStatus>,
    /// Full reasoning content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<Vec<ReasoningTextContent>>,
}

impl From<responses::ReasoningItem> for ReasoningItem {
    fn from(item: responses::ReasoningItem) -> Self {
        let status = item.status.map(OutputStatus::from);

        let content = item.content.map(|contents| {
            contents
                .into_iter()
                .map(ReasoningTextContent::from)
                .collect()
        });

        Self {
            id: item.id.to_owned(),
            status,
            content,
        }
    }
}

/// A single content block within an output message.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum MessageContent {
    /// Textual content.
    OutputText { text: String },
    /// Refusal message when the model declines to answer.
    Refusal { refusal: String },
    /// Reasoning content
    ReasoningText { text: String },
    #[serde(other)]
    /// Any other content type we are not explicitly modeling.
    Unknown,
}

impl From<responses::OutputMessageContent> for MessageContent {
    fn from(item: responses::OutputMessageContent) -> Self {
        match item {
            responses::OutputMessageContent::OutputText(output_text_content) => {
                MessageContent::OutputText {
                    text: output_text_content.text.to_owned(),
                }
            }
            responses::OutputMessageContent::Refusal(refusal_content) => MessageContent::Refusal {
                refusal: refusal_content.refusal.to_owned(),
            },
        }
    }
}

impl From<responses::OutputContent> for MessageContent {
    fn from(item: responses::OutputContent) -> Self {
        match item {
            responses::OutputContent::OutputText(output_text_content) => {
                MessageContent::OutputText {
                    text: output_text_content.text.to_owned(),
                }
            }
            responses::OutputContent::Refusal(refusal_content) => MessageContent::Refusal {
                refusal: refusal_content.refusal.to_owned(),
            },

            responses::OutputContent::ReasoningText(reasoning_text_content) => {
                MessageContent::ReasoningText {
                    text: reasoning_text_content.text.to_owned(),
                }
            }
        }
    }
}

/// One block of reasoning text, used in both `summary` and `content` of
/// reasoning items.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ReasoningTextContent {
    pub text: String,
}

impl From<responses::ReasoningTextContent> for ReasoningTextContent {
    fn from(item: responses::ReasoningTextContent) -> Self {
        Self {
            text: item.text.to_owned(),
        }
    }
}

/// o-series reasoning settings.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Default)]
pub struct Reasoning {
    /// Constrains effort on reasoning for
    /// [reasoning models](https://platform.openai.com/docs/guides/reasoning).
    /// Currently supported values are `minimal`, `low`, `medium`, and `high`. Reducing
    /// reasoning effort can result in faster responses and fewer tokens used
    /// on reasoning in a response.
    ///
    /// Note: The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<ReasoningEffort>,
    /// A summary of the reasoning performed by the model. This can be
    /// useful for debugging and understanding the model's reasoning process.
    /// One of `auto`, `concise`, or `detailed`.
    ///
    /// `concise` is only supported for `computer-use-preview` models.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<ReasoningSummary>,
}

impl From<responses::Reasoning> for Reasoning {
    fn from(item: responses::Reasoning) -> Self {
        let effort = item.effort.map(ReasoningEffort::from);
        let summary = item.summary.map(ReasoningSummary::from);

        Self { effort, summary }
    }
}

/// Usage statistics for a response.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ResponseUsage {
    /// The number of input tokens.
    pub input_tokens: u32,
    /// The number of output tokens.
    pub output_tokens: u32,
    /// A detailed breakdown of the output tokens.
    pub output_tokens_details: responses::OutputTokenDetails,
    /// The total number of tokens used.
    pub total_tokens: u32,
}

impl From<responses::ResponseUsage> for ResponseUsage {
    fn from(item: responses::ResponseUsage) -> Self {
        Self {
            input_tokens: item.input_tokens,
            output_tokens: item.output_tokens,
            output_tokens_details: item.output_tokens_details.to_owned(),
            total_tokens: item.total_tokens,
        }
    }
}

/// Status of input/output items.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum OutputStatus {
    InProgress,
    Completed,
    Incomplete,
}

impl From<responses::OutputStatus> for OutputStatus {
    fn from(item: responses::OutputStatus) -> Self {
        match item {
            responses::OutputStatus::InProgress => OutputStatus::InProgress,
            responses::OutputStatus::Completed => OutputStatus::Completed,
            responses::OutputStatus::Incomplete => OutputStatus::Incomplete,
        }
    }
}

/// Details about an incomplete response.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct IncompleteDetails {
    /// The reason why the response is incomplete.
    pub reason: String,
}

impl From<responses::IncompleteDetails> for IncompleteDetails {
    fn from(item: responses::IncompleteDetails) -> Self {
        Self {
            reason: item.reason.to_owned(),
        }
    }
}

/// Error returned by the API when a request fails.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct ErrorObject {
    /// The error code for the response.
    pub code: String,
    /// A human-readable description of the error.
    pub message: String,
}

impl From<responses::ErrorObject> for ErrorObject {
    fn from(item: responses::ErrorObject) -> Self {
        Self {
            code: item.code.to_owned(),
            message: item.message.to_owned(),
        }
    }
}

#[derive(Clone, Serialize, Debug, Deserialize, PartialEq, Default)]
#[serde(rename_all = "lowercase")]
pub enum ReasoningEffort {
    None,
    Minimal,
    Low,
    #[default]
    Medium,
    High,
}

impl From<responses::ReasoningEffort> for ReasoningEffort {
    fn from(item: responses::ReasoningEffort) -> Self {
        match item {
            responses::ReasoningEffort::Minimal => ReasoningEffort::Minimal,
            responses::ReasoningEffort::Low => ReasoningEffort::Low,
            responses::ReasoningEffort::Medium => ReasoningEffort::Medium,
            responses::ReasoningEffort::High => ReasoningEffort::High,
            responses::ReasoningEffort::None => ReasoningEffort::None,
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ReasoningSummary {
    Auto,
    Concise,
    Detailed,
}

impl From<responses::ReasoningSummary> for ReasoningSummary {
    fn from(item: responses::ReasoningSummary) -> Self {
        match item {
            responses::ReasoningSummary::Auto => ReasoningSummary::Auto,
            responses::ReasoningSummary::Concise => ReasoningSummary::Concise,
            responses::ReasoningSummary::Detailed => ReasoningSummary::Detailed,
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Status {
    Completed,
    Failed,
    InProgress,
    Cancelled,
    Queued,
    Incomplete,
}

impl From<responses::Status> for Status {
    fn from(item: responses::Status) -> Self {
        match item {
            responses::Status::Completed => Status::Completed,
            responses::Status::Failed => Status::Failed,
            responses::Status::InProgress => Status::InProgress,
            responses::Status::Cancelled => Status::Cancelled,
            responses::Status::Queued => Status::Queued,
            responses::Status::Incomplete => Status::Incomplete,
        }
    }
}
